### ISSUE TITLE
[AD] Fix flaky tests

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-dashboards-functional-test#278]
For 2.2 release, several flaky tests were seen in the gh runners. Tracking those failures here to be fixed for 2.3 release.

**Comment by ohltyler** [comment]
```
  1) Historical results page
       Sample detector
         Aggregations render anomalies:
     CypressError: Timed out retrying after 60050ms: `cy.click()` failed because this element:

`<label class="euiButtonGroupButton euiButtonGroupButton--text euiButtonGroupButton--small" for="i92b7b861-1908-11ed-a7e5-b1792f060f66">...</label>`

is being covered by another element:

`<select class="euiSelect euiSelect--compressed" aria-label="Time unit" aria-describedby="ia36e48e1-1908-11ed-a7e5-b1792f060f66 ia36e48e2-1908-11ed-a7e5-b1792f060f66">...</select>`

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureDescendents (http://localhost:5601/__cypress/runner/cypress_runner.js:164076:78)
      at ensureDescendents (http://localhost:5601/__cypress/runner/cypress_runner.js:150263:8)
      at ensureDescendentsAndScroll (http://localhost:5601/__cypress/runner/cypress_runner.js:150270:14)
      at ensureElIsNotCovered (http://localhost:5601/__cypress/runner/cypress_runner.js:150402:5)
      at runAllChecks (http://localhost:5601/__cypress/runner/cypress_runner.js:150592:52)
      at retryActionability (http://localhost:5601/__cypress/runner/cypress_runner.js:150616:16)
      at tryCatcher (http://localhost:5601/__cypress/runner/cypress_runner.js:13022:23)
      at Function.Promise.attempt.Promise.try (http://localhost:5601/__cypress/runner/cypress_runner.js:10296:29)
      at whenStable (http://localhost:5601/__cypress/runner/cypress_runner.js:168808:63)
      at http://localhost:5601/__cypress/runner/cypress_runner.js:168305:14
      at tryCatcher (http://localhost:5601/__cypress/runner/cypress_runner.js:13022:23)
      at Promise._settlePromiseFromHandler (http://localhost:5601/__cypress/runner/cypress_runner.js:10957:31)
      at Promise._settlePromise (http://localhost:5601/__cypress/runner/cypress_runner.js:11014:18)
      at Promise._settlePromise0 (http://localhost:5601/__cypress/runner/cypress_runner.js:11059:10)
      at Promise._settlePromises (http://localhost:5601/__cypress/runner/cypress_runner.js:11139:18)
      at Promise._fulfill (http://localhost:5601/__cypress/runner/cypress_runner.js:11083:18)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js:230:32)
```

**Comment by ohltyler** [comment]
@jackiehanyang feel free to add any more flaky failures you were seeing in your testing here

**Comment by ohltyler** [comment]
+ @amitgalitz if you've seen any recent failures

**Comment by amitgalitz** [comment]
This historical test has stopped producing flaky results but I am keeping this issue open as we have now noticed new flaky tests on the main branch. Both flaky and potentially non-flaky failures have been mentioned on this issue in ad-dashboard.

For the purpose of this issue the relevant flaky failure is on the `AD Dashboard Page` tests: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/381

**Comment by CCongWang** [comment]
Hi @amitgalitz , do you still see flaky tests? can we close this issue?

**Comment by CCongWang** [comment]
Removing v2.5.0 label for now, feel free to add proper labels
