### ISSUE TITLE
[BUG] Windows Cypress requires to use cypress@^10.8.0 to resolve path separator issues

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-dashboards-functional-test#370]
Hi All,

2.4.0 cypress windows CI on github failed with these error:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3383921006/jobs/5620287472#step:14:159
```

  1) Create datasources
       should successfully load the page:
     AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Create a new data source connection to help you retrieve data from an external OpenSearch compatible source.' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress\integration\core-opensearch-dashboards\opensearch-dashboards\datasource-management-plugin\1_create_datasource.spec.js:123:10)

  2) Create datasources
       should successfully show the experimental feature callout:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-test-subj="data-source-experimental-call"]`, but never found it.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress\integration\core-opensearch-dashboards\opensearch-dashboards\datasource-management-plugin\1_create_datasource.spec.js:128:62)
```

Related to Cypress version have to update to at least 10.8.0:
* When searching for specs we now normalize OS-specific path separators so that Windows users can use back- and forward-slashes. Fixes [#23426](https://github.com/cypress-io/cypress/issues/23426).
* https://docs.cypress.io/guides/references/changelog#10-8-0

Thanks.

**Comment by peterzhuamazon** [comment]
Seems like cypress 10 does not support cypress.json anymore and requires some migration:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3384251969/jobs/5620995705#step:11:85

```
There is a cypress.json file at the path: D:\a\opensearch-dashboards-functional-test\opensearch-dashboards-functional-test\cypress-test

Cypress version 10.0.0 no longer supports cypress.json.

Please run cypress open to launch the migration tool to migrate to cypress.config.{js,ts,mjs,cjs}.

https://on.cypress.io/migration-guide

```

**Comment by tianleh** [comment]
Will do after 2.4.0 release

**Comment by bbarani** [comment]
@tianleh @seanneumann @seraphjiang Lets target this for 1.3.7 release [scheduled](https://opensearch.org/releases.html) for Dec 08 2022

**Comment by CEHENKLE** [comment]
> @tianleh @seanneumann @seraphjiang Lets target this for 1.3.7 release [scheduled](https://opensearch.org/releases.html) for Dec 08 2022

Yes, please.

**Comment by dblock** [comment]
Renamed the issue to upgrade to 10+, assigned to @tianleh.

**Comment by peterzhuamazon** [comment]
Latest development to use cypress 9 version is also running, the reason it failed is because data source is not enabled as well as vis_builder.

**Comment by tianleh** [comment]
> Latest development to use cypress 9 version is also running, the reason it failed is because data source is not enabled as well as vis_builder.

Great! In this case, do we still need to handle Cypress 10 upgrade as a priority, especially for 1.3.7? @peterzhuamazon

**Comment by peterzhuamazon** [comment]
> > Latest development to use cypress 9 version is also running, the reason it failed is because data source is not enabled as well as vis_builder.
> 
> Great! In this case, do we still need to handle Cypress 10 upgrade as a priority, especially for 1.3.7? @peterzhuamazon

Hi @tianleh this is not a priority now, we are able to run cypress on Windows for the past week and it runs well.
Although upgrading to v10 would still be nice for the long term later.

Thanks.

**Comment by tianleh** [comment]
Sure. Let me remove the `1.3.7` label then
