### ISSUE TITLE
[BUG] 1_create_datasource.spec.js fail due to multiple submit

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-dashboards-functional-test#439]
### What is the bug?
Currently, `1_create_datasource.spec.js` test suite fails due to multiple submit element found in the test. Details error log is pasted below:

```
Running:  core-opensearch-dashboards/opensearch-dashboards/datasource-manageme          (15 of 17)
            nt-plugin/1_create_datasource.spec.js                                                   


  Create datasources
    ✓ should successfully load the page (7821ms)
    ✓ should successfully show the experimental feature callout
    Datasource can be created successfully
      1) with no auth and all required inputs
      2) with basic auth and all required inputs
      3) with no auth and all inputs
      4) with basic auth and all inputs
    Title validation
      ✓ validate that title is a required field
      5) validate that title cannot use existing datasource name
      ✓ validate that title field does not show any error if title is valid and unique
    Description validation
      ✓ validate that description field does not show any error if the field is empty
      ✓ validate that description field does not show any error if there is a description
    Endpoint validation
      ✓ validate that endpoint is a required field
      ✓ validate that endpoint field cannot use invalid format of URL
      ✓ validate that endpoint field does not show any error if URL is valid
    Username validation
      ✓ validate that username field does not show when auth type is no auth
      ✓ validate that username is a required field when auth type is username & password
      ✓ validate that username field does not show any error when auth type is username & password and field is not empty
    Password validation
      ✓ validate that password field does not show when auth type is no auth
      ✓ validate that password is a required field when auth type is username & password
      ✓ validate that password field does not show any error when auth type is username & password and field is not empty
    Create datasource button
      ✓ validate if create data source connection button is disabled when first visit this page
      ✓ validate if create data source connection button is disabled when there is any field error
      ✓ validate if create data source connection button is not disabled only if there is no any field error


  18 passing (2m)
  5 failing

  1) Create datasources
       Datasource can be created successfully
         with no auth and all required inputs:
     CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.

https://on.cypress.io/click
      at mouseAction (http://localhost:5601/__cypress/runner/cypress_runner.js:152534:76)
      at Context.click (http://localhost:5601/__cypress/runner/cypress_runner.js:152713:14)
      at Context.<anonymous> (http://localhost:5601/__cypress/runner/cypress_runner.js:173267:19)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js:135:35)

  2) Create datasources
       Datasource can be created successfully
         with basic auth and all required inputs:
     CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.

https://on.cypress.io/click
      at mouseAction (http://localhost:5601/__cypress/runner/cypress_runner.js:152534:76)
      at Context.click (http://localhost:5601/__cypress/runner/cypress_runner.js:152713:14)
      at Context.<anonymous> (http://localhost:5601/__cypress/runner/cypress_runner.js:173267:19)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js:146:35)

  3) Create datasources
       Datasource can be created successfully
         with no auth and all inputs:
     CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.

https://on.cypress.io/click
      at mouseAction (http://localhost:5601/__cypress/runner/cypress_runner.js:152534:76)
      at Context.click (http://localhost:5601/__cypress/runner/cypress_runner.js:152713:14)
      at Context.<anonymous> (http://localhost:5601/__cypress/runner/cypress_runner.js:173267:19)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js:156:35)

  4) Create datasources
       Datasource can be created successfully
         with basic auth and all inputs:
     CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.

https://on.cypress.io/click
      at mouseAction (http://localhost:5601/__cypress/runner/cypress_runner.js:152534:76)
      at Context.click (http://localhost:5601/__cypress/runner/cypress_runner.js:152713:14)
      at Context.<anonymous> (http://localhost:5601/__cypress/runner/cypress_runner.js:173267:19)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js:168:35)

  5) Create datasources
       Title validation
         validate that title cannot use existing datasource name:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `input[name="dataSourceTitle"]:invalid`, but never found it.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js:181:57)
```

### How can one reproduce the bug?
Just check recent submitted PRs or run this test.

### What is the expected behavior?
Fix the bug

**Comment by ananzh** [comment]
This error is due to the below line of code in the test suite
```
cy.get('[type="submit"]').click();
```
There are two buttons have `type="submit"`. So we see 
```
cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.
```

<img width="1461" alt="Screen Shot 2023-01-10 at 13 20 57" src="https://user-images.githubusercontent.com/79961084/211668516-483a23ae-4d86-4e40-8e01-af9970c5fe57.png">

Apparently, `type` is not a unique identity to locate the element. `data-test-subj` is a more common property to identify an element.
