### ISSUE TITLE
[BUG] sanity tests are failing for visualize and discover

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#52]
**What is the bug?**
A clear and concise description of the bug.

```
Running:  opensearch-dashboards/without-security/dashboard_sanity_test_spec.js            (1 of 1)


  dashboard sample data validation
    checking home page
      ✓ checking opensearch_dashboards_overview display (2498ms)
      ✓ checking tutorial_directory display
      ✓ checking management display
      ✓ checking dev_tools display
      ✓ settings display
      ✓ checking feature_directory display
      ✓ checking navigation display
      ✓ checking Help menu display
    checking Visualize
      1) checking visualizations list display
      2) checking search bar display
      3) checking create visualization button display
    checking discover
      4) checking save query button display
      5) checking query input display
      6) checking refresh button display
      7) checking add filter button display
      8) checking index pattern switch button display
      9) checking field filter display
    adding sample data
      ✓ checking ecommerce dashboards displayed (15026ms)
      ✓ checking flights dashboards displayed (2634ms)
      ✓ checking web logs dashboards displayed (2397ms)
      checking index patterns
        ✓ checking ecommerce index patterns are added (1068ms)
        ✓ checking flights index patterns are added (62ms)
        ✓ checking web logs index patterns are added
      checking saved objects
        ✓ checking ecommerce object is saved (1000ms)
        ✓ checking flights object is saved (58ms)
        ✓ checking web logs object is saved (48ms)
    checking Dev Tools
      ✓ checking welcome panel display (779ms)
      ✓ checking dismiss button display (141ms)
      ✓ checking console input area display
      ✓ checking console output area display
    checking stack management
      ✓ checking Stack Management display (736ms)
      ✓ checking index patterns link display (38ms)
      ✓ checking saved objects link display
      ✓ checking advance settings link display


  25 passing (10m)
  9 failing

  1) dashboard sample data validation
       checking Visualize
         checking visualizations list display:
     AssertionError: Timed out retrying: Expected to find element: `div[data-test-subj="itemsInMemTable"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:169:16)

  2) dashboard sample data validation
       checking Visualize
         checking search bar display:
     AssertionError: Timed out retrying: Expected to find element: `input[placeholder="Search..."]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:172:16)

  3) dashboard sample data validation
       checking Visualize
         checking create visualization button display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="newItemButton"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:175:16)

  4) dashboard sample data validation
       checking discover
         checking save query button display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="saved-query-management-popover-button"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:185:16)

  5) dashboard sample data validation
       checking discover
         checking query input display:
     AssertionError: Timed out retrying: Expected to find element: `textarea[data-test-subj="queryInput"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:188:16)

  6) dashboard sample data validation
       checking discover
         checking refresh button display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="querySubmitButton"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:191:16)

  7) dashboard sample data validation
       checking discover
         checking add filter button display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="addFilter"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:194:16)

  8) dashboard sample data validation
       checking discover
         checking index pattern switch button display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="indexPattern-switch-link"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:197:16)

  9) dashboard sample data validation
       checking discover
         checking field filter display:
     AssertionError: Timed out retrying: Expected to find element: `button[data-test-subj="toggleFieldFilterButton"]`, but never found it.
      at CommonUI.checkElementExists (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:491:35)
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/opensearch-dashboards/without-security/dashboard_sanity_test_spec.js:200:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        34                                                                               │
  │ Passing:      25                                                                               │
  │ Failing:      9                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  9                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     9 minutes, 30 seconds                                                            │
  │ Spec Ran:     opensearch-dashboards/without-security/dashboard_sanity_test_spec.js             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking Visualize -- checking visualizations list display (failed).png                 
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking Visualize -- checking search bar display (failed).png                          
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking Visualize -- checking create visualization button display (faile               
     d).png                                                                                         
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking save query button display (failed).png                    
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking query input display (failed).png                          
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking refresh button display (failed).png                       
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking add filter button display (failed).png                    
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking index pattern switch button display (failed               
     ).png                                                                                          
  -  /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/screenshots/opensearch-dashboa     (1280x720)
     rds/without-security/dashboard_sanity_test_spec.js/dashboard sample data validat               
     ion -- checking discover -- checking field filter display (failed).png                         


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
    Compression progress:  66%
  -  Finished processing: /tmp/tmpo0wypu9n/functionalTestDashboards/cypress/videos/op   (15 seconds)
                          ensearch-dashboards/without-security/dashboard_sanity_test_               
                          spec.js.mp4                                                               


================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  opensearch-dashboards/without-secur      09:30       34       25        9        -        - │
  │    ity/dashboard_sanity_test_spec.js                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     09:30       34       25        9        -        -  

```
**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by tianleh** [comment]
https://user-images.githubusercontent.com/60111637/144736805-ba5bd0b6-32d6-4601-807a-ad512d26efe5.mp4

**Comment by tianleh** [comment]
Suspicious commit 
https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/d8e15f6397a3a8e0203fe97e230ae63545f1a206

**Comment by tianleh** [comment]
Verified from infra side that the tests are successful. Thanks for the fix.
