### ISSUE TITLE
[BUG] AD tests fail on security-enabled cluster when `plugins.security.system_indices.enabled:true`

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-dashboards-functional-test#645]
### What is the bug?
When `plugins.security.system_indices.enabled` is set to `true`, in `opensearch.yml`, security-enabled tests will fail since AD is using a custom cmd to delete system indices to cleanup test resources after running some of the test suites.

When the security setting is enabled, it blocks any DELETE requests against system indices by default. Because of this, the system index doesn't get deleted, there are leftover test resources after running some of the test suites, and the subsequent tests can fail due to unexpected resources still existing in the cluster (test indices, test detectors, etc.).

**Comment by seraphjiang** [comment]
@ohltyler 

do we know what block ` it blocks any DELETE requests `?

it is because permission setup?

i didn't find any error/test fail from https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4745708789/jobs/8428403568

would you add share a failed test run job to help understand this issue

**Comment by peterzhuamazon** [comment]
Issues started in 2.6.0 to current 2.8.0 release.

```
  Running:  plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js             (1 of 8)


  Create detector workflow
    1) "after each" hook for "Full creation - based on real index"


  0 passing (26s)
  1 failing

  1) Create detector workflow
       "after each" hook for "Full creation - based on real index":
     CypressError: `cy.request()` failed on:

https://localhost:9200/.opendistro-anomaly*

The response we received from your web server was:

  > 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: DELETE
URL: https://localhost:9200/.opendistro-anomaly*
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/112.0.5615.165 Safari/537.36",
  "accept": "*/*",
  "cookie": "security_authentication=Fe26.2**ee290319a7a5343aded95dff5288e25ab33aca0d61bf654181aa83355e10ca82*Jz6YM52FFExqD3iMztxy3w*i45fhMkm9txtJQI6rKfnWwO96QABH-ypQlTgQFt5YbpaWBaoqnaS7hcAcTyTV31ymuAtwDNMpSWxUfwn4X3ujAdEEZPlzg_Ct_POIXHPZu27dBue3tPdzZYu-3HpdxHk-wCbCdGbgJAWPmJZCvESQ9VfKRDqtsxAOhXWFHenCxNyzvlArF9R9nO4Ws9DazK2MJBTZmZ7oxOAipBbj7Q-Rw**7332c2b2e0a4eb7e6d577d487a8b49071aefa9479d24b981c806809506e07251*KQMth0xKWGjHCUpNHf8Z27_Gw2zYq_YotPschTHMsdY",
  "authorization": "Basic YWRtaW46YWRtaW4=",
  "accept-encoding": "gzip, deflate",
  "content-length": 0
}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  "content-type": "application/json; charset=UTF-8",
  "content-length": "297"
}
Body: {
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
  },
  "status": 403
}


https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Create detector workflow`
      at http://localhost:5601/__cypress/runner/cypress_runner.js:160667:80
      at tryCatcher (http://localhost:5601/__cypress/runner/cypress_runner.js:13022:23)
      at Promise._settlePromiseFromHandler (http://localhost:5601/__cypress/runner/cypress_runner.js:10957:31)
      at Promise._settlePromise (http://localhost:5601/__cypress/runner/cypress_runner.js:11014:18)
      at Promise._settlePromise0 (http://localhost:5601/__cypress/runner/cypress_runner.js:11059:10)
      at Promise._settlePromises (http://localhost:5601/__cypress/runner/cypress_runner.js:11139:18)
      at _drainQueueStep (http://localhost:5601/__cypress/runner/cypress_runner.js:7729:12)
      at _drainQueue (http://localhost:5601/__cypress/runner/cypress_runner.js:7722:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:5601/__cypress/runner/cypress_runner.js:7738:5)
      at Async.drainQueues (http://localhost:5601/__cypress/runner/cypress_runner.js:7608:14)
  From Your Spec Code:
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/support/index.js:368:6)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     25 seconds                                                                       │
  │ Spec Ran:     plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /tmp/tmpod_59grz/anomalyDetectionDashboards/cypress/screenshots/plugins/anomaly-     (1280x720)
     detection-dashboards-plugin/create_detector_spec.js/Create detector workflow --                
     Full creation - based on real index -- after each hook (failed).png                            


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /tmp/tmpod_59grz/anomalyDetectionDashboards/cypress/videos/    (2 seconds)
                          plugins/anomaly-detection-dashboards-plugin/create_detector               
                          _spec.js.mp4                                                              
```

**Comment by peterzhuamazon** [comment]
Related to this:
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/554
